"""add_dato_ine_valor_mercado_indexes

Revision ID: c1b80c16bdda
Revises: 0001
Create Date: 2026-03-18 20:11:01.325550+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'c1b80c16bdda'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datos_ine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('indicador', sa.String(length=50), nullable=False),
    sa.Column('anno', sa.Integer(), nullable=False),
    sa.Column('trimestre', sa.Integer(), nullable=True),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('unidad', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('indicador', 'anno', 'trimestre', name='uq_dato_ine')
    )
    op.create_index(op.f('ix_datos_ine_anno'), 'datos_ine', ['anno'], unique=False)
    op.create_index('ix_datos_ine_indicador_anno', 'datos_ine', ['indicador', 'anno'], unique=False)
    op.create_table('valores_mercado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barrio_id', sa.Integer(), nullable=True),
    sa.Column('anno', sa.Integer(), nullable=False),
    sa.Column('trimestre', sa.Integer(), nullable=True),
    sa.Column('precio_euro_m2', sa.Float(), nullable=False),
    sa.Column('num_muestras', sa.Integer(), nullable=True),
    sa.Column('portal', sa.String(length=50), nullable=True),
    sa.Column('tipo_inmueble', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['barrio_id'], ['barrios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_valores_mercado_anno'), 'valores_mercado', ['anno'], unique=False)
    op.create_index('ix_valores_mercado_anno_barrio', 'valores_mercado', ['anno', 'barrio_id'], unique=False)
    op.create_index('ix_visados_anno_fuente', 'visados_estadisticos', ['anno', 'fuente'], unique=False)
    op.create_index('ix_visados_anno_tipo', 'visados_estadisticos', ['anno', 'tipo_obra'], unique=False)
    op.create_index('ix_visados_fuente', 'visados_estadisticos', ['fuente'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_visados_fuente', table_name='visados_estadisticos')
    op.drop_index('ix_visados_anno_tipo', table_name='visados_estadisticos')
    op.drop_index('ix_visados_anno_fuente', table_name='visados_estadisticos')
    op.drop_index('ix_valores_mercado_anno_barrio', table_name='valores_mercado')
    op.drop_index(op.f('ix_valores_mercado_anno'), table_name='valores_mercado')
    op.drop_table('valores_mercado')
    op.drop_index('ix_datos_ine_indicador_anno', table_name='datos_ine')
    op.drop_index(op.f('ix_datos_ine_anno'), table_name='datos_ine')
    op.drop_table('datos_ine')
    # ### end Alembic commands ###
